### ISSUE TITLE
log

### ISSUE THREAD

**Issue by nimoc** [nimojs/web-design-notes#10]

**Comment by Grifree** [comment]
setTimeout(function() {
    console.log('e');
},0);
new Promise(function(resolve) {
    console.log('a') ;
    for (var i = 0; i < 10000; i++) {
        i == 9999 && resolve()
    };
    console.log('rr');
}).then(function() {
    console.log('v');
});
console.log('i');

**Comment by Grifree** [comment]
a

**Comment by Grifree** [comment]
(a) 某岛主要居民是其实和无赖两部分. 骑士只讲真话, 无赖只说假话. 甲和乙是该岛上的两个居民, 关于他们,甲说:"或者我是无赖,或者乙是骑士."
A. 甲和乙都是骑士
B. 甲和乙都是无赖
C. 甲是骑士, 乙是无赖
D. 乙是骑士, 甲是无赖
E. 无法断定

**Comment by Grifree** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
20:32 a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
request

**Comment by nimojs** [comment]
response

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
company

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
h？

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
132-1632-9736

**Comment by nimojs** [comment]
## tip 
- 没有电话确认
- 没有实地考察
- 没有商讨长租价格是否优惠

## [游天下] http://www.youtx.com

- http://www.youtx.com/room/291120/
	price:  $179/天 , (包水电) , 满7天$161/天 , 满30天$143/天
	add: 大柏树
	des: 宾馆标房14平
- http://www.youtx.com/room/312441/
	price: $179/天 , 水电另计(冷水18/吨，热水28/吨，电费：2块/度) , 满30天$140/天 , 清洁$30
	add: 曲阳路801号(大柏树站向东600米)
	des: 宾馆标房18平

## [蚂蚁短租] https://www.mayi.com/

- https://www.mayi.com/room/851198205?ca_name=hz_fang10_mayi_tiezilaiyuan&ca_source=ganji&ca_s=tg_ganji&ca_n=mayi_fang10_tiezi&gj_other_uuid=4655856410912989026078&gj_other_ifid=from_ganji&gj_other_city_id=12&gj_other_sid=d6fa53a7b92e49d2b73ee47487f4a6a3&gj_other_gc_1=fang&gj_other_ca_n=-&gj_other_ca_s=seo_baidu&gj_other_ca_i=-
	price: $198/天
	add: 闸北区大宁路街道阳城路283弄大华阳城花园(离公司1公里)
	des: 一居室整租65平
- https://www.mayi.com/room/850046611?ca_name=hz_fang10_mayi_tiezi&ca_source=ganji&ca_s=tg_ganji&ca_n=mayi_fang10_tiezi&gj_other_uuid=4655856410912989026078&gj_other_ifid=from_ganji&gj_other_city_id=12&gj_other_sid=d6fa53a7b92e49d2b73ee47487f4a6a3&gj_other_gc_1=fang&gj_other_ca_n=-&gj_other_ca_s=seo_baidu&gj_other_ca_i=-
	price: $198/天 , 满7天9.3折，满30天8.3折
	add: 闸北区彭浦街道安业路300弄安业路300弄(1号线共康路站=电瓶回家时间路程一致)
	des: 一居室整租41平
- https://www.mayi.com/room/850953128?ca_name=hz_fang10_mayi_tiezilaiyuan&ca_source=ganji&ca_s=tg_ganji&ca_n=mayi_fang10_tiezi&gj_other_uuid=4655856410912989026078&gj_other_ifid=from_ganji&gj_other_city_id=12&gj_other_sid=d6fa53a7b92e49d2b73ee47487f4a6a3&gj_other_gc_1=fang&gj_other_ca_n=-&gj_other_ca_s=seo_baidu&gj_other_ca_i=-#
	price: $99/天 , 水电另计(冷水18/吨，热水28/吨，电费：2块/度) , (包水电$178/天) , 清洁$30
	add: 曲阳路801号(大柏树站向东600米)
	des: 宾馆标房12平
- https://www.mayi.com/room/850851716?ca_name=hz_fang10_mayi_tiezilaiyuan&ca_source=ganji&ca_s=tg_ganji&ca_n=mayi_fang10_tiezi&gj_other_uuid=4655856410912989026078&gj_other_ifid=from_ganji&gj_other_city_id=12&gj_other_sid=d6fa53a7b92e49d2b73ee47487f4a6a3&gj_other_gc_1=fang&gj_other_ca_n=-&gj_other_ca_s=seo_baidu&gj_other_ca_i=-
	price: $198/天 , 清洁$30
	add: 曲阳路801号(大柏树站向东600米)
	des: 宾馆标房20平
- http://www.mayi.com/room/851326677
	price: $140/天 , 满7天9.5折
	add: 宝山区高境街道殷高西路10弄寓见公寓(3号线殷高西路站)
	des: 一居室整租30平
- http://www.mayi.com/room/851084580
	price: $168/天 , 满7天9.0折
	add: 虹口区凉城街道水电路凉城路口灵新小区1013弄33号(你家附近)
	des: 一居室整租33平
- http://www.mayi.com/room/851283724
	price: $150/天 
	add: 虹口区大柏树街道新市南路新市家园(你家附近)
	des: 一居室整租45平
- http://www.mayi.com/room/850364617
	price: $168/天 , 满30天9折
	add: 普陀区光新街道中山北路(离公司西南方向3公里)
	des: 一居室整租30平

## [ 途家 ] https://www.tujia.com/

- https://www.tujia.com/shanghai_gongyu/jinganqu_224037.htm#index=20
	price: $180/天 
	add: 1号线延长路
	des: 一居室整租41平
- https://www.tujia.com/shanghai_gongyu/hongkouqu_318592.htm#unitmap
	price: $178/天 
	add: 曲阳路801号(大柏树站向东600米)
	des: 宾馆标房12平
- https://www.tujia.com/shanghai_gongyu/putuoqu_48309.htm#unitmap
	price: $161/天 
	add: 普陀区武宁路1500号(据公司5公里)
	des: 宾馆大床房17平
- https://www.tujia.com/shanghai_gongyu/putuoqu_84159.htm#index=4
	price: $158/天 , 水电另计
	add: 普陀区石泉路35弄宏骅公寓3楼(据公司西南方向5公里)
	des: 一居室复式房整租
- https://www.tujia.com/shanghai_gongyu/putuoqu_84120.htm#index=3
	price: $138/天 , 水电另计
	add: 普陀区石泉路35弄宏骅公寓3楼(据公司西南方向5公里)
	des: 一居室复式房整租

## [ 58同城 ] http://sh.58.com

- http://sh.58.com/zufang/31173393521850x.shtml?from=1-list-1&iuType=p_0&PGTID=0d3090a7-005c-b4b7-97e7-d74a0c83a2f2&ClickID=3
	price: $1600/月
	add: 凉城路1319号公寓住房
	des: 一居室整租15平

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a
秋高气爽, 恰逢市井生活

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a
sunday home

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
aaaaaaaaaaaaaaaaaaaaa

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
不会用安卓.... a now

**Comment by nimojs** [comment]
a       WYWK

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a forget

**Comment by nimojs** [comment]
回不到过去，麻木于现状，却又看不到未来。——真·《the failing song》

**Comment by nimojs** [comment]
平面上有5条平行直线与另一组n条平行直线垂直。若两组平行直线共构成280个矩形。则n=（）
A.5  B.6  C.7  D.8

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
```
box1           box2           box3
blue            red         blue & red


1. 所有的标示都是错误的
2. 但确实是有 一个只有红色的 一个只有蓝色的，一个有红和蓝的
3. 每个盒子里面都有多个糖果


问： 拿几次糖果可以判断出正确的标识
```

**Comment by nimojs** [comment]
```
box1           box2           box3
blue            red         blue & red


1. 所有的标示都是错误的
2. 但确实是有 一个只有红色的 一个只有蓝色的，一个有红和蓝的
3. 每个盒子里面都有多个糖果


问： 拿几次糖果可以判断出正确的标识
```

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
a

**Comment by nimojs** [comment]
https://pan.baidu.com/s/1hspe3Ak
