### ISSUE TITLE
文章内容的一点疑问？

### ISSUE THREAD

**Issue by rccoder** [nimojs/web-design-notes#6]
> 例如浏览者的分辨率是 1280x800 则最小宽度不可小于 1240 1280 - 40 = 1240，因为网页可能会出现滚动条或一些工具栏。所以需要减去 40 像素。

为什么是不可小于1240 ？ 按照我的理解是不可大于1240（因为有工具栏等......

**Comment by nimoc** [comment]
写错了，感谢指正，应该是不可大于 1240

**Comment by rccoder** [comment]
@nimojs  :+1:

**Comment by rccoder** [comment]
这儿还是有点绕口

直接变成 **宽度不可大于1240**最为直接，建议去掉**最小**二字

**Comment by nimoc** [comment]
已调整 https://github.com/nimojs/web-design-notes/commit/154dc70a23c6e3b85e4cfe2f5315e8144a7aa788
@rccoder  :+1:
